# Generated by Django 4.0.2 on 2022-02-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='twitter_user_id',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='user',
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
