# Generated by Django 4.0.2 on 2022-02-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0002_remove_twitteruser_twitter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='profile_image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='url',
            field=models.URLField(default='http://'),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
