# Generated by Django 4.0 on 2021-12-10 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwittterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('description', models.TextField(max_length=280)),
                ('favourites_count', models.PositiveBigIntegerField()),
                ('followers_count', models.PositiveBigIntegerField()),
                ('friends_count', models.PositiveBigIntegerField()),
                ('twitter_id', models.PositiveBigIntegerField()),
                ('lang', models.CharField(max_length=50)),
                ('listed_count', models.PositiveBigIntegerField()),
                ('location', models.CharField(max_length=280)),
                ('name', models.CharField(max_length=280)),
                ('profile_background_image_url', models.URLField(max_length=280)),
                ('profile_background_image_url_https', models.URLField(max_length=280)),
                ('profile_banner_url', models.URLField(max_length=500)),
                ('profile_banner_url_https', models.URLField(max_length=500)),
                ('screen_name', models.CharField(max_length=280)),
                ('verified', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.PositiveBigIntegerField()),
                ('text', models.CharField(max_length=280)),
                ('twitter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_user', to='tweet_manager.twittteruser')),
            ],
        ),
    ]
