# Generated by Django 3.2.9 on 2021-12-11 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='twitter_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_user_for_tweet', to='tweet_manager.twittteruser'),
        ),
        migrations.CreateModel(
            name='TwitterUserMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newest_id', models.PositiveBigIntegerField()),
                ('oldest_id', models.PositiveBigIntegerField()),
                ('result_count', models.IntegerField()),
                ('next_token', models.CharField(max_length=100)),
                ('previous_token', models.CharField(max_length=100)),
                ('twitter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_user_for_meta_data', to='tweet_manager.twittteruser')),
            ],
        ),
    ]
