# Generated by Django 3.2.9 on 2021-12-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_manager', '0002_auto_20211211_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterusermetadata',
            name='newest_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitterusermetadata',
            name='next_token',
            field=models.CharField(default='NO_TOKEN', max_length=100),
        ),
        migrations.AlterField(
            model_name='twitterusermetadata',
            name='oldest_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitterusermetadata',
            name='previous_token',
            field=models.CharField(default='NO_TOKEN', max_length=100),
        ),
        migrations.AlterField(
            model_name='twitterusermetadata',
            name='result_count',
            field=models.IntegerField(default=0),
        ),
    ]
