# Generated by Django 3.2.9 on 2022-02-21 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0005_auto_20220221_0913'),
        ('tweet_manager', '0003_auto_20211212_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='twitter_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_user_for_tweet', to='UserManager.twitteruser'),
        ),
        migrations.AlterField(
            model_name='twitterusermetadata',
            name='twitter_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_user_for_meta_data', to='UserManager.twitteruser'),
        ),
        migrations.DeleteModel(
            name='TwittterUser',
        ),
    ]
