# Generated by Django 3.2.9 on 2022-02-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_manager', '0004_auto_20220221_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_analysed',
            field=models.BooleanField(default=False),
        ),
    ]
