# Generated by Django 3.2.9 on 2022-02-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_manager', '0005_tweet_is_analysed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='sentiment',
            field=models.BooleanField(default=False),
        ),
    ]
