# Generated by Django 3.2.9 on 2022-02-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_manager', '0006_auto_20220222_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='sentiment',
            field=models.CharField(max_length=100),
        ),
    ]
