# Generated by Django 3.2.9 on 2022-02-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_manager', '0007_alter_tweet_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='tweet',
            name='label',
            field=models.CharField(default='NOT_CLASSIFIED', max_length=100),
        ),
    ]
