# Generated by Django 3.2.9 on 2022-02-27 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_manager', '0010_timeseriessummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseriessummary',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 5, 0, 6, 827699)),
        ),
    ]
