# Generated by Django 3.2.9 on 2022-02-27 05:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_manager', '0011_timeseriessummary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseriessummary',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 5, 2, 21, 117966, tzinfo=utc)),
        ),
    ]
