# Generated by Django 3.2.9 on 2022-02-27 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_manager', '0013_alter_timeseriessummary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseriessummary',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
