# Generated by Django 3.2.9 on 2022-02-27 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_manager', '0014_alter_timeseriessummary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseriessummary',
            name='date',
            field=models.DateField(default=datetime.date(2022, 2, 27)),
        ),
    ]
