# Generated by Django 3.2.9 on 2022-02-27 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_manager', '0015_alter_timeseriessummary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseriessummary',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 6, 0, 4, 358301)),
        ),
    ]
