# Generated by Django 3.2.9 on 2022-03-02 13:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_manager', '0016_alter_timeseriessummary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseriessummary',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 2, 13, 1, 3, 984735, tzinfo=utc)),
        ),
    ]
