# Generated by Django 3.2.9 on 2022-03-02 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_manager', '0017_alter_timeseriessummary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseriessummary',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
